---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Changing perm of "{{ osx_script }}", adding "+x"
  file: dest={{ osx_script }} mode=a+x
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false
